
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saveh
 */
public class Home extends javax.swing.JFrame {
    public int i=0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(239, 59));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\two arrow.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrowBtn(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 143, -1));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\add new patient.png")); // NOI18N
        jButton2.setText("Add Patient");
        jButton2.setActionCommand("addPatient");
        jButton2.setPreferredSize(new java.awt.Dimension(239, 59));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtn(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\rsz_history1.png")); // NOI18N
        jButton4.setText("History");
        jButton4.setActionCommand("HistoryBtn");
        jButton4.setPreferredSize(new java.awt.Dimension(239, 59));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\rsz_update_details.png")); // NOI18N
        jButton5.setText("Update Details");
        jButton5.setActionCommand("Update DetailsBtn");
        jButton5.setPreferredSize(new java.awt.Dimension(239, 59));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDetails(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\rsz_hospital_information.png")); // NOI18N
        jButton6.setActionCommand("InformationBtn");
        jButton6.setLabel("Information");
        jButton6.setPreferredSize(new java.awt.Dimension(239, 59));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\exit.png")); // NOI18N
        jButton7.setText("LogOut");
        jButton7.setActionCommand("LogOutBtn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 231, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\saveh\\OneDrive\\Documents\\NetBeansProjects\\HospitalApp\\HMS ICON\\home.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -2, 1400, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout
        int a = JOptionPane.showConfirmDialog(null, "Are u sure u want to log out?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
            
            
        }
        
      
        
    }//GEN-LAST:event_Logout

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new History().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UpdateDetails(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDetails
        new UpdateDetails().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateDetails

    private void ArrowBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrowBtn
if(i==0){
    jButton2.setLocation(90,30);
    
    jButton4.setLocation(570,30);
    jButton5.setLocation(819,30);
    jButton6.setLocation(1000,33);
    jButton6.setLocation(1000,30);
    i=1;
}
else
{
    jButton2.setLocation(10,110);

    jButton4.setLocation(10,261);
    jButton5.setLocation(10,338);
    jButton6.setLocation(10,416);
    jButton7.setLocation(10,499);
    
    i=0;
}
    }//GEN-LAST:event_ArrowBtn

    private void AddPatientBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtn
new NewPatient().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPatientBtn

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   new Information().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
